# @package _global_

# https://wandb.ai
logger:
  wandb:
    _target_: lightning.pytorch.loggers.wandb.WandbLogger
    name: null # name of the run; set from the command line (e.g. logger.wandb.name=...)
    save_dir: "${paths.output_dir}"
    offline: False
    id: null # pass correct id to resume experiment!
    anonymous: null # enable anonymous logging
    project: "lmask_feasible"
    log_model: False # upload lightning ckpts
    prefix: "" # a string to put at the beginning of metric keys
    # entity: "" # set to name of your wandb team
    group: ""
    tags: []
    job_type: ""

hydra:
  run:
    dir: ${paths.log_dir}/runs/${logger.wandb.group}/${logger.wandb.name}/${now:%Y-%m-%d}_${now:%H}
  sweep:
    dir: ${paths.log_dir}/multiruns/${logger.wandb.group}/${logger.wandb.name}/${now:%Y-%m-%d}_${now:%H}
    subdir: ${hydra.job.num}
  job_logging:
    handlers:
      file:
        class: logging.FileHandler
        filename: ${paths.log_dir}/runs/${logger.wandb.group}/${logger.wandb.name}/${now:%Y-%m-%d}_${now:%H}/run.log
        formatter: simple